version: '3'
services:
  pgdb_v2:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5400:5432"
    expose:
      - '5411'
      # Where our data will be persisted
    volumes:
      - postgres-data:/var/lib/postgres/data/
    networks:
      - postgres
# Names our volume
  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pshirsat.cci@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 9091:80
    networks:
      - postgres

volumes:
  postgres-data:
  pgadmin:
networks:
  postgres: